version: '3.8'

services:
  dds_simulator:
    build:
      context: .
      dockerfile: Dockerfile
    image: dds-simulator-app:latest
    container_name: dds_app_sim
    network_mode: "host" # Wajib agar multicast DDS discovery berfungsi antar host/container
    environment:
      - SHIP_ID=${SHIP_ID}
      - CYCLONEDDS_URI=file:///etc/cyclonedds/cyclonedds.xml
    volumes:
      - ./cyclonedds.xml:/etc/cyclonedds/cyclonedds.xml:ro
      - ${CERTS_PATH}:/etc/cyclonedds/certs:ro
    stdin_open: true    # Mencegah EOF error pada std::cin
    tty: true           # Memungkinkan tampilan menu console interaktif
